name: Scrape Disney Times

on:
  schedule:
    - cron: "*/10 0-4,13-23 * * *"

jobs:
  build:
    name: Scrape-Times
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Deno Module
        uses: denolib/setup-deno@master

      - name: Scrape
        run: deno run --unstable --allow-net --allow-write --allow-read get_data.ts

      - name: Publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"
